#!/bin/sh
### BEGIN INIT INFO
# Provides:          mongodb
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Mongodb startup script
# Description:       Mongodb start stop daemon sends SIGINT to terminate
#                    say man signal to see details
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin:/opt/mongo
DESC="Mongodb Service"
NAME=mongod
DAEMON=/usr/bin/$NAME
DAEMON_ARGS="--config /etc/mongod.conf"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

[ -x "$DAEMON" ] || exit 0
. /lib/init/vars.sh
. /lib/lsb/init-functions

do_start()
{
        start-stop-daemon -Sbm -p $PIDFILE --exec $DAEMON -- $DAEMON_ARGS 
	echo "Started $DESC"

}

do_stop()
{
	start-stop-daemon --stop --signal 2 -q --pidfile $PIDFILE --name $NAME
	rm -f $PIDFILE
	echo "Stopped $DESC"
}

case "$1" in
  start)
	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop}" >&2
	exit 3
	;;
esac

exit 0

